### ISSUE TITLE
Implement watch mode for code generation so it automatically gets generated while running development mode.

### ISSUE THREAD

**Issue by paales** [tonyfromundefined/next-starter#3]

**Comment by tonyfromundefined** [comment]
Receiving the GraphQL schema and automatically generating code through it should only work when the schema of the GraphQL API changes. Therefore, we need to watch the GraphQL schema, which is not related to the client code.

Therefore, the feature you mentioned is not going to be implemented later. If you want to generate code generation before `yarn dev`, add `yarn generate` to `scripts.predev` in package.json

```json
{
  "scripts": {
    "predev": "yarn generate",
    "dev": "node ./index.js",
    "prebuild": "rimraf ./dist",
    "build": "next build ./src",
    "postbuild": "parallel-webpack",
    "deploy:dev": "sls deploy --stage dev",
    "deploy:stage": "NODE_ENV=production sls deploy --stage stage",
    "deploy:prod": "NODE_ENV=production sls deploy --stage prod",
    "lint": "tslint --project '.'",
    "pregenerate": "get-graphql-schema `dotenv -e .env.development -p NEXT_APP_GRAPHQL_ENDPOINT` > ./src/generated/schema.graphql",
    "generate": "graphql-codegen --config codegen.yml"
  }
}
```

But, I didn't update it in this repository. Because, `yarn dev` should work normally even when offline.
